schema_version = "1.0.0"

id = "all_objects_into_assets"
version = "1.0.2"
name = "All Objects into Assets"
tagline = "Create collection assets and catalogs automatically"
maintainer = "StellArc"
type = "add-on"
blender_version_min = "4.5.0"
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Read/write asset library catalogs file"
